#!/bin/bash

###############
# PREPARACION #
###############

if [ $(whoami) != "root" ]; then
  echo "Necesitas ser root"
  exit 1
fi

source "/usr/local/JSBach/config/variables.conf"
conf_file="$DIR$PROYECTO$DIR_CONF/$CONF_IFWAN"

[ -f $conf_file ] || touch $conf_file
source $conf_file

function mod_conf_param () {
	param=$1
	new_value=$2

	if grep -q "^$param=" $conf_file; then
		sed -i 's/^'$param'=.*/'$param'='$new_value'/' $conf_file
	else
		echo "$param=$new_value" >> $conf_file
	fi
}

function del_conf_param () {
	param=$1

	sed -i 's/^'$param'=.*/'$param'=/' $conf_file
}



########
# MAIN #
########
case $1 in
  --start)
	if [ -z $IFWAN ] || [ -z $MODE ]; then
		echo "WARN: No hay una intefaz de red configurada." &&
		echo "Configúrela y vuelva a intentarlo."
	  	exit 1; 
	fi

	if $(curl -m 5 https://www.google.com &>/dev/null); then
		echo "ERROR: La tarjeta $IFWAN ya está activada."
		exit 1
	fi

	case $MODE in
		dhcp)
			{ dhcpcd $IFWAN &>/dev/null  && echo "DHCP activo"; } ||
			echo "La configuración DHCP en $IFWAN ha fallado."
			;;
		manual)
			ip l s dev $IFWAN up &>/dev/null && echo "Tarjeta UP"
			ip a a $IP/$MASC dev $IFWAN &>/dev/null && echo "IP configurada"
			ip r a default via $PE &>/dev/null && echo "Ruta DEFAULT configurada"

			if grep -q "^#DNS=" /etc/systemd/resolved.conf; then
				sed -i "s/^#DNS=.*/DNS=$DNS/" /etc/systemd/resolved.conf
			elif grep -q "^DNS=" /etc/systemd/resolved.conf; then
				sed -i "s/^DNS=.*/DNS=$DNS/" /etc/systemd/resolved.conf
			else
				echo "DNS=$DNS" >> /etc/systemd/resolved.conf
			fi

			systemctl restart systemd-resolved
			;;

	esac
	;;

  --stop)
	if [ -z $IFWAN ] || [ -z $MODE ]; then
		echo "WARN: No hay una intefaz de red configurada." &&
		echo "Configúrela y vuelva a intentarlo."
	  	exit 1; 
	fi

	{
		{ dhcpcd -k $IFWAN &>/dev/null && echo "DHCP parado en $IFWAN"; } || {
		       echo "Deteniendo $IFWAN..."
		       ip a d $IP/$MASC dev $IFWAN &>/dev/null && echo "IP eliminada" 
		       ip l s dev $IFWAN down &>/dev/null && echo "Tarjeta detenida"; 
		}; 
	} || echo "ERROR: La interfaz $IFWAN ya se encuentra parada."
	;;

  --restart)
          if [ -z $IFWAN ] || [ -z $MODE ]; then
		echo "WARN: No hay una intefaz de red configurada." &&
		echo "Configúrela y vuelva a intentarlo."
	  	exit 1; 
	  fi
	  bash ./ifwan --stop && bash ./ifwan --start
	  ;;
  --config)
	MODE=$2
	shift 2
	case $MODE in
		dhcp)
			if [ $# -ne 1 ]; then
				echo "Cantidad de argumentos incorrecta."
				echo "Uso: ifwan --config dhcp <ifwan>"
				exit 1
			else
				echo "Se ha guardado la siguiente configuración:"
				echo "MODE=dhcp"
				echo "IFWAN=$1"
				echo ""
				echo "A continuación, puede aplicar la configuración con <a href="./action-ifwan.cgi?param=--start">IFWAN START</a>"
					
				mod_conf_param MODE dhcp
				mod_conf_param IFWAN $1

				del_conf_param IP
				del_conf_param MASC
				del_conf_param PE
				del_conf_param DNS
			fi
			;;
			
		manual)
			if [ $# -ne 4 ]; then
				echo "Cantidad de argumentos incorrecta."
				echo "Uso: ifwan --config manual <ifwan> <ip>/<mascara> <pe> <dns>"
				exit 1
			else
				IFWAN=$1
				IP=$(echo $2 | cut -d "/" -f 1)
				MASC=$(echo $2 | cut -d "/" -f 2)
				PE=$3
				DNS=$4

				if [ -z $IP ] || [ -z $MASC ]; then
					echo "No ha introducido una IP válida."
					echo "Ejemplo: 192.168.0.10/24"
					exit 1
				else
					echo "Se ha guardado la siguiente configuración:"
					echo "MODE=manual"
					echo "IFWAN=$IFWAN"
					echo "IP=$IP"
					echo "MASC=$MASC"
					echo "PE=$PE"
					echo "DNS=$DNS"
					echo ""
					echo "A continuación, puede aplicar la configuración con <a href="./action-ifwan.cgi?param=--start">IFWAN START</a>"
				fi

				mod_conf_param MODE manual
				mod_conf_param IFWAN $IFWAN
				mod_conf_param IP $IP
				mod_conf_param MASC $MASC
				mod_conf_param PE $PE
				mod_conf_param DNS $DNS

			fi
			;;

		*)
			echo "Uso: ifwan --config [dhcp|manual]"
			exit 1
			;;
		esac
	;;

  --status)
	if [ -z $IFWAN ] || [ -z $MODE ]; then
		echo "WARN: No hay una intefaz de red configurada." &&
		echo "Configúrela y vuelva a intentarlo."
	  	exit 1; 
	fi

	if curl --interface $IFWAN -m 5 https://www.google.com &>/dev/null ; then
		echo "WAN ACTIVADA en $IFWAN"
	else
	       	echo "WAN DESACTIVADA en $IFWAN"
	fi

	;;

  *)
	echo "Uso: ifwan --[start|stop|restart|config|status]"
	exit 1
	;;
esac
exit 0
