#!/bin/bash

###############
# PREPARACION #
###############

if [ $(whoami) != "root" ]; then
  echo "Necesitas ser root"
  exit 1
fi

source "/usr/local/JSBach/config/variables.conf"
conf_file="$DIR/$PROYECTO/$DIR_CONF/$CONF_IFWAN"

[ -f $conf_file ] || touch $conf_file
source $conf_file

function mod_conf_param () {
	param=$1
	new_value=$2

	if grep -q "^$param=" $conf_file; then
		sed -i 's/^'$param'=.*/'$param'='$new_value'/' $conf_file
	else
		echo "$param=$new_value" >> $conf_file
	fi
}

function del_conf_param () {
	param=$1

	sed -i 's/^'$param'=.*/'$param'=/' $conf_file
}



########
# MAIN #
########
case $1 in
  --start)
	if [ -z $IFW_IFWAN ] || [ -z $IFW_MODE ]; then
		echo "WARN: No hay una intefaz de red configurada." &&
		echo "Configúrela y vuelva a intentarlo."
	  	exit 1; 
	fi

	if $(curl -m 5 https://www.google.com &>/dev/null); then
		echo "ERROR: La tarjeta $IFW_IFWAN ya está activada."
		exit 1
	fi

	case $IFW_MODE in
	dhcp)
			{ dhcpcd $IFW_IFWAN &>/dev/null  && echo "DHCP activo"; } ||
			echo "La configuración DHCP en $IFW_IFWAN ha fallado."
			;;
		manual)
			ip l s dev $IFW_IFWAN up &>/dev/null && echo "Tarjeta UP"
			ip a a $IFW_IP/$IFW_MASC dev $IFW_IFWAN &>/dev/null && echo "IP configurada"
			ip r a default via $IFW_PE &>/dev/null && echo "Ruta DEFAULT configurada"

			if grep -q "^#DNS=" /etc/systemd/resolved.conf; then
				sed -i "s/^#DNS=.*/DNS=$IFW_DNS/" /etc/systemd/resolved.conf
			elif grep -q "^DNS=" /etc/systemd/resolved.conf; then
				sed -i "s/^DNS=.*/DNS=$IFW_DNS/" /etc/systemd/resolved.conf
			else
				echo "DNS=$IFW_DNS" >> /etc/systemd/resolved.conf
			fi

			systemctl restart systemd-resolved
			;;

	esac
	;;

  --stop)
	if [ -z $IFW_IFWAN ] || [ -z $IFW_MODE ]; then
		echo "WARN: No hay una intefaz de red configurada." &&
		echo "Configúrela y vuelva a intentarlo."
	  	exit 1; 
	fi

	{
		{ dhcpcd -k $IFW_IFWAN &>/dev/null && echo "DHCP parado en $IFW_IFWAN"; } || {
		       echo "Deteniendo $IFW_IFWAN..."
		       ip a d $IFW_IP/$IFW_MASC dev $IFW_IFWAN &>/dev/null && echo "IP eliminada" 
		       ip l s dev $IFW_IFWAN down &>/dev/null && echo "Tarjeta detenida"; 
		}; 
	} || echo "ERROR: La interfaz $IFW_IFWAN ya se encuentra parada."
	;;

  --restart)
          if [ -z $IFW_IFWAN ] || [ -z $IFW_MODE ]; then
		echo "WARN: No hay una intefaz de red configurada." &&
		echo "Configúrela y vuelva a intentarlo."
	  	exit 1; 
	  fi
	  bash ./ifwan --stop && bash ./ifwan --start
	  ;;
  --config)
	IFW_MODE=$2
	shift 2
	case $IFW_MODE in
		dhcp)
			if [ $# -ne 1 ]; then
				echo "Cantidad de argumentos incorrecta."
				echo "Uso: ifwan --config dhcp <ifwan>"
				exit 1
			else
				echo "Se ha guardado la siguiente configuración:"
				echo "IFW_MODE=dhcp"
				echo "IFW_IFWAN=$1"
				echo ""
				echo "A continuación, puede aplicar la configuración con <a href="./action-ifwan.cgi?param=--start">IFWAN START</a>"
					
				mod_conf_param IFW_MODE dhcp
				mod_conf_param IFW_IFWAN $1

				del_conf_param IFW_IP
				del_conf_param IFW_MASC
				del_conf_param IFW_PE
				del_conf_param IFW_DNS
			fi
			;;
			
		manual)
			if [ $# -ne 4 ]; then
				echo "Cantidad de argumentos incorrecta."
				echo "Uso: ifwan --config manual <ifwan> <ip>/<mascara> <pe> <dns>"
				exit 1
			else
				IFW_IFWAN=$1
				IFW_IP=$(echo $2 | cut -d "/" -f 1)
				IFW_MASC=$(echo $2 | cut -d "/" -f 2)
				IFW_PE=$3
				IFW_DNS=$4

				if [ -z $IFW_IP ] || [ -z $IFW_MASC ]; then
					echo "No ha introducido una IP válida."
					echo "Ejemplo: 192.168.0.10/24"
					exit 1
				else
					echo "Se ha guardado la siguiente configuración:"
					echo "IFW_MODE=manual"
					echo "IFW_IFWAN=$IFWAN"
					echo "IFW_IP=$IP"
					echo "IFW_MASC=$MASC"
					echo "IFW_PE=$PE"
					echo "IFW_DNS=$DNS"
					echo ""
					echo "A continuación, puede aplicar la configuración con <a href="./action-ifwan.cgi?param=--start">IFWAN START</a>"
				fi

				mod_conf_param IFW_MODE manual
				mod_conf_param IFW_IFWAN $IFWAN
				mod_conf_param IFW_IP $IP
				mod_conf_param IFW_MASC $MASC
				mod_conf_param IFW_PE $PE
				mod_conf_param IFW_DNS $DNS

			fi
			;;

		*)
			echo "Uso: ifwan --config [dhcp|manual]"
			exit 1
			;;
		esac
	;;

  --status)
	if [ -z $IFW_IFWAN ] || [ -z $IFW_MODE ]; then
		echo "WARN: No hay una intefaz de red configurada." &&
		echo "Configúrela y vuelva a intentarlo."
	  	exit 1; 
	fi

	if curl --interface $IFW_IFWAN -m 5 https://www.google.com &>/dev/null; then
		echo "WAN ACTIVADA en $IFW_IFWAN"
	else
	       	echo "WAN DESACTIVADA en $IFW_IFWAN"
	fi

	;;

  *)
	echo "Uso: ifwan --[start|stop|restart|config|status]"
	exit 1
	;;
esac
exit 0
